# Generated by Django 5.1.2 on 2024-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
