# Generated by Django 5.1.2 on 2024-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
