# Generated by Django 5.1.2 on 2024-11-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_post_is_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_pickup',
        ),
    ]
