# Generated by Django 5.1.2 on 2024-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='Club',
            field=models.ManyToManyField(to='employ.club', verbose_name='部活'),
        ),
        migrations.AddField(
            model_name='employ',
            name='adress',
            field=models.CharField(blank=True, max_length=20, verbose_name='住所'),
        ),
    ]
