# Generated by Django 5.1.2 on 2024-10-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='time',
            new_name='title',
        ),
    ]
